baseURL = 'https://petergreenwell.com/'
languageCode = 'en-au'
DefaultContentLanguage = "en-au"
title = 'Peter Greenwell'
theme = 'lugo'
author = "Peter Greenwell"
copyright = "© 2024 - forever Peter Greenwell."
enableEmoji = true
pagination.pagerSize = 3
enableInlineShortcodes = true
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

[markup]

  [markup.goldmark.extensions.extras.mark]
    enable = true  

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true